services:

  minio-b:
    image: quay.io/minio/minio
    container_name: minio-colaa-b
    ports:
      - "9200:9000"
      - "9201:9001"
    volumes:
      - ./data/minio-b:/data
    environment:
      MINIO_ROOT_USER: colaa-b
      MINIO_ROOT_PASSWORD: PasswordB123!
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

